controllers:
    resource: ../src/Controller/
    type: attribute

# Route par défaut qui redirige vers le gestionnaire de backup
home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: backup_index
        permanent: false
