name: ${PROJET_NAME}

services:
  app:
    build:
      context: ./${APP_DIR}/
      dockerfile: Dockerfile
      args:
        - DOCKER_USER=${DOCKER_USER}
        - DOCKER_USER_ID=${DOCKER_USER_ID}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
        - APP_DIR=${APP_DIR}
    container_name: ${PROJET_NAME}-${APP_NAME}
    volumes:
        - ./${APP_DIR}/config/apache:/etc/apache2/sites-enabled
        - ../${APP_DIR}://var/www/${APP_DIR}:cached
        - ~/.config/rclone:/home/${DOCKER_USER}/rcloneConfig
        - ${RCLONE_LOCAL_PATH}://var/www/${APP_DIR}/localData
    ports:
        - "${APP_HTTP_PORT}:80"
    restart: always
    networks:
      - network

networks:
    network:
